apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: supermario
  namespace: argocd
spec:
  destination:
    namespace: supermario
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest
    repoURL: 'https://github.com/fsavoia/mariohtml5'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
