apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demoifood-eksctl
  region: us-east-1
  version: "1.22"

# vpc:
#   subnets:
#     private:
#       us-east-1a: { id: "subnet-011c744d1ee8a0eec" }
#       us-east-1b: { id: "subnet-09865fe62cef87e7a" }
#       us-east-1c: { id: "subnet-047a1e518b156d9e0" }

nodeGroups:
  - name: "ng-1-workers"
    instanceType: t3.small
    desiredCapacity: 3
    privateNetworking: true

cloudWatch:
 clusterLogging:
   enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:us-east-1:652839185683:key/abf363f2-4766-44ef-b066-df4f9c36d5d6
