apiVersion: v1
kind: Namespace
metadata:
  name: loadgen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgen
  name: loadgen
  namespace: loadgen
spec:
  replicas: 4
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      nodeSelector:
          eks.amazonaws.com/nodegroup: "ng_managed"
      containers:
      - command:
        - /bin/sh
        - -c
        - while sleep 0.01; do wget -q -O- http://supermario-svc.supermario:8080; done
        image: busybox:1.28
        name: busybox
        resources:
          requests:
            cpu: 128m
            memory: 128M
          limits:
            cpu: 128m
            memory: 128M

