apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: supermario-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: supermario-deployment
  minReplicas: 1
  maxReplicas: 200
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    # - type: Resource
    #   resource:
    #     name: cpu
    #     target:
    #       type: Utilization
    #       averageUtilization: 40