apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario-deployment
  namespace: default
  labels:
    app: supermario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermario
  template:
    metadata:
      labels:
        app: supermario
    spec:
      topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: supermario
      nodeSelector:
          karpenter: "true"
      tolerations:
      - key: "kubernetes.io/karpenter-taint"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: supermario
        image: 652839185683.dkr.ecr.sa-east-1.amazonaws.com/helloworld-grpc:supermario
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: 200m
