apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermario-deployment
  namespace: supermario
  labels:
    app: supermario
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:    
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: supermario
  template:
    metadata:
      labels:
        app: supermario
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: supermario
      containers:
      - name: supermario
        image: nginx
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "126Mi"
            cpu: 50m
          limits:
            memory: "126Mi"
            cpu: 50m